### ISSUE TITLE
t/00-compile.t fail on "perl in space"

### ISSUE THREAD

**Issue by mohawk2** [cpan-testers/Test-Reporter-Transport-Metabase#1]
Same applies here:

https://metacpan.org/source/DAGOLDEN/Test-Reporter-Transport-Metabase-1.999008/t/00-compile.t

**Comment by mohawk2** [comment]
(Also metacpan's showing confusion about the "repository" information)

**Comment by dagolden** [comment]
Shipped new release to CPAN without compile test.
